allowBuilds:
  core-js: false
  esbuild: true
minimumReleaseAgeExclude:
  - '@atproto/common-web@0.5.9'
  - '@atproto/lexicon@0.7.11'
  - '@atproto/oauth-client-browser@0.5.3'
  - '@atproto/oauth-client@0.8.3'
  - '@atproto/syntax@0.7.4'
  - '@atproto/xrpc@0.8.10'
